(()=>{
  const byId=id=>document.getElementById(id),dialog=byId('mathGameDialog'),open=byId('mathGameOpen'),rankingDialog=byId('mathRankingDialog'),status=byId('mathGameSaveStatus');
  const games={math:{title:'すうしきドロップ',file:'math-game.html',result:'math-drop-result',unit:'問'},mole:{title:'数字もぐら',file:'number-mole.html',result:'number-mole-result',unit:'回'},drop:{title:'ナンバードロップ',file:'number-drop.html',result:'number-drop-result',unit:'個'},maze:{title:'三本道迷路',file:'three-paths.html',result:'three-paths-result',unit:'本'}};Object.assign(games,{"order":{"title":"順番タップ","file":"order-tap.html","result":"order-game-result","unit":"個"},"color":{"title":"色当て","file":"color-match.html","result":"color-game-result","unit":"問"},"chest":{"title":"宝箱えらび","file":"treasure-choice.html","result":"chest-game-result","unit":"回"}});games.formwork={title:'型枠の組立て',file:'formwork-game.html',result:'formwork-game-result',unit:'点'};games.flash={title:'フラッシュ暗算',file:'flash-math.html',result:'flash-math-result',unit:'問'};games.runner={title:'ハイスピードラン',file:'high-speed-run.html',result:'runner-result',unit:'m'};games.math30={title:'すうしきドロップ・30秒チャレンジ',file:'math-game.html',result:'math-drop-result',unit:'点'};let currentGame='math',rankingGame='math';let identity=null,busy=false,loading=false,automaticRankingGame=null;const pending=new Map();const pendingKey='pastime-unsaved-scores-v1';
  try{for(const entry of JSON.parse(localStorage.getItem(pendingKey)||'[]'))if(games[entry.gameId]&&entry.gameId!=='formwork'&&typeof entry.name==='string'&&Number.isInteger(entry.score)&&entry.score>=(['math','math30'].includes(entry.gameId)?-100000:0)&&entry.score<=100000)pending.set(entry.gameId+':'+entry.name,entry);}catch{}
  function keepPending(){try{localStorage.setItem(pendingKey,JSON.stringify([...pending.values()].map(({name,gameId,score})=>({name,gameId,score}))));}catch{}}
  let rankingView=0;
  function cacheKey(gameId){return 'pastime-ranking-v1:'+API+':'+byId('employee').value+':'+gameId;}
  function cached(gameId){try{const value=JSON.parse(localStorage.getItem(cacheKey(gameId))||'null');if(value&&Array.isArray(value.rows)&&value.rows.every(r=>typeof r.name==='string'&&(r.score===null||Number.isInteger(r.score))&&(r.rank===null||Number.isInteger(r.rank))))return value;}catch{}return null;}
  function remember(gameId,rows){try{localStorage.setItem(cacheKey(gameId),JSON.stringify({time:Date.now(),rows}));}catch{}}
  function savedBest(gameId,name){const c=cached(gameId);if(!c||Date.now()-c.time>300000)return null;return c.rows.find(r=>r.name===name)?.score??null;}
  function previous(gameId){byId('mathRankingRows').textContent='最新ランキングを取得中…';status.textContent='最新情報を確認しています…';return false;}
  gameReady.then(ok=>{if(ok&&pending.size)savePending();});
  async function request(payload){if(!API)return {ok:false,error:'共有先が未設定です'};let timer;try{return await Promise.race([callShared(payload),new Promise(resolve=>{timer=setTimeout(()=>resolve({ok:false,error:'ランキングの応答を確認できません。勤怠アプリから開き直してください。'}),65000)})]);}catch{return {ok:false,error:'通信できませんでした'};}finally{clearTimeout(timer);}}
  async function authenticate(){if(!await verifyPunchIdentity())return null;const r=readDeviceRegistration();if(!r||r.name!==byId('employee').value)return null;return {name:r.name,deviceToken:r.deviceToken};}
  function render(rows){window.dispatchEvent(new CustomEvent("game-ranking-updated",{detail:{gameId:rankingGame,rows}}));const box=byId('mathRankingRows');box.replaceChildren();if(!rows.length){box.textContent='登録メンバーがいません';return;}const table=document.createElement('table');table.className='report';const head=document.createElement('tr');for(const label of ['順位','メンバー','最高得点']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const row of rows){const tr=document.createElement('tr');for(const text of [row.rank===null?'—':row.rank+'位',row.name,row.score===null?'未プレイ':row.score+games[rankingGame].unit]){const td=document.createElement('td');td.textContent=text;tr.append(td);}table.append(tr);}box.append(table);}
  async function showRanking(gameId=rankingGame){if(busy){status.textContent='得点を保存中です。保存後にランキングを表示します。';return;}if(loading)return;rankingGame=gameId;const view=++rankingView;byId('gameRankingTitle').textContent=games[gameId].title+'・ランキング';loading=true;try{const who=await authenticate();if(!who)return;const frame=byId('mathGameFrame');frame?.contentWindow.postMessage({type:'math-drop-pause'},'*');if(!rankingDialog.open)rankingDialog.showModal();const hadCache=previous(gameId);if(!hadCache)byId('mathRankingRows').textContent='読み込み中…';const result=await request({action:'mathGameRanking',gameId,...who});if(result.ok&&Array.isArray(result.ranking)){remember(gameId,result.ranking);if(view===rankingView&&!busy){render(result.ranking);status.textContent='最新のランキングです';}}else if(view===rankingView){if(hadCache)status.textContent='前回のランキングです。更新できません：'+(result.error||'通信を確認してください');else byId('mathRankingRows').textContent=result.error||'ランキングを取得できません';}}finally{loading=false;}}
  async function savePending(){if(busy||!pending.size)return;busy=true;status.textContent='得点を保存中…';byId('mathGameRetry').hidden=true;let failed=false,lastSaved=null;for(const [key,entry] of [...pending]){if(entry.name!==byId('employee').value)continue;const result=await request({action:'saveMathGameScore',...entry});if(!result.ok||!Array.isArray(result.ranking)){status.textContent='得点を保存できません：'+(result.error||'Apps Scriptを更新してください');failed=true;if(automaticRankingGame===entry.gameId&&rankingDialog.open){const box=byId('mathRankingRows');box.textContent=status.textContent;const retry=document.createElement('button');retry.className='primary';retry.textContent='保存してランキングを表示';retry.onclick=()=>{box.textContent='得点を保存中…';savePending();};box.append(document.createElement('br'),retry);}break;}remember(entry.gameId,result.ranking);window.dispatchEvent(new CustomEvent("game-ranking-updated",{detail:{gameId:entry.gameId,rows:result.ranking}}));if(pending.get(key)===entry)pending.delete(key);keepPending();lastSaved=entry;if(automaticRankingGame===entry.gameId&&rankingDialog.open&&rankingGame===entry.gameId)render(result.ranking);}busy=false;byId('mathGameRetry').hidden=!pending.size;if(!failed){status.textContent=(lastSaved?games[lastSaved.gameId].title+'の':'')+'最高得点をランキングに保存しました';if([...pending.values()].some(e=>e.name===byId('employee').value))savePending();}}
  function gameButton(gameId){if(['order','color','chest','formwork','flash','runner'].includes(gameId))return byId(gameId+'GameOpen');return byId(gameId==='maze'?'mazeGameOpen':gameId==='mole'?'moleGameOpen':gameId==='drop'?'dropGameOpen':'mathGameOpen')}
  async function openGame(gameId){const trigger=gameButton(gameId);if(trigger.disabled)return;trigger.disabled=true;try{const who=await authenticate();if(!who)return;identity=who;currentGame=gameId;const frame=document.createElement('iframe');frame.id='mathGameFrame';frame.title=games[gameId].title;frame.setAttribute('sandbox','allow-scripts');frame.src='./'+games[gameId].file;dialog.append(frame);dialog.showModal();byId('mathGamePlayer').textContent=games[gameId].title+' ・ '+who.name+' さん';}finally{trigger.disabled=false;}}
  open.addEventListener('click',()=>openGame('math'));byId('moleGameOpen').addEventListener('click',()=>openGame('mole'));byId('dropGameOpen').addEventListener('click',()=>openGame('drop'));byId('mazeGameOpen').addEventListener('click',()=>openGame('maze'));
  for(const id of ['order','color','chest','formwork','flash','runner']){byId(id+'GameOpen').addEventListener('click',()=>openGame(id));byId(id+'RankingOpen')?.addEventListener('click',()=>showRanking(id));}
  byId('mathGameClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{byId('mathGameFrame')?.remove();const trigger=gameButton(currentGame);identity=null;trigger.focus();});
  window.addEventListener('message',event=>{const returnFrame=byId('mathGameFrame');if(currentGame==='math'&&returnFrame&&event.source===returnFrame.contentWindow&&event.origin==='null'&&event.data?.type==='math-drop-back'){if(rankingDialog.open)rankingDialog.close();dialog.close();return;}const frame=byId('mathGameFrame'),message=event.data;if(!frame||event.source!==frame.contentWindow||event.origin!=='null'||!identity||message?.type!==games[currentGame].result||!Number.isInteger(message.score)||message.score<(currentGame==='math'?-100000:0)||message.score>100000)return;if(!API){status.textContent='おためしの得点：'+message.score+games[currentGame].unit+'（ランキングには保存されません）';return;}const resultGame=currentGame==='math'&&message.gameMode==='challenge'?'math30':currentGame;automaticRankingGame=resultGame;rankingGame=resultGame;++rankingView;byId('gameRankingTitle').textContent=games[resultGame].title+'・ランキング';if(!rankingDialog.open)rankingDialog.showModal();const hasPrevious=previous(resultGame);if(!hasPrevious)byId('mathRankingRows').textContent='得点を保存してランキングを読み込んでいます…';const key=resultGame+':'+identity.name;const best=savedBest(resultGame,identity.name);if(best!==null&&message.score<=best&&!pending.has(key)){status.textContent='今回 '+message.score+games[resultGame].unit+'・最高得点の更新はありません';if(!busy&&!loading)showRanking(resultGame);return;}const prior=pending.get(key);if(!prior||message.score>prior.score)pending.set(key,{...identity,gameId:resultGame,score:message.score});keepPending();savePending();});
  byId('math30RankingOpen').addEventListener('click',()=>showRanking('math30'));byId('mathRankingOpen').addEventListener('click',()=>showRanking('math'));byId('moleRankingOpen').addEventListener('click',()=>showRanking('mole'));byId('dropRankingOpen').addEventListener('click',()=>showRanking('drop'));byId('mazeRankingOpen').addEventListener('click',()=>showRanking('maze'));byId('mathRankingRefresh').addEventListener('click',()=>showRanking());byId('mathRankingClose').addEventListener('click',()=>rankingDialog.close());byId('mathGameRetry').addEventListener('click',savePending);
})();
