(()=>{
  const byId=id=>document.getElementById(id),dialog=byId('mathGameDialog'),open=byId('mathGameOpen'),rankingDialog=byId('mathRankingDialog'),status=byId('mathGameSaveStatus');
  const games={math:{title:'すうしきドロップ',file:'math-game.html',result:'math-drop-result',unit:'問'},mole:{title:'数字もぐら',file:'number-mole.html',result:'number-mole-result',unit:'回'},drop:{title:'ナンバードロップ',file:'number-drop.html',result:'number-drop-result',unit:'個'},maze:{title:'三本道迷路',file:'three-paths.html',result:'three-paths-result',unit:'本'}};Object.assign(games,{"order":{"title":"順番タップ","file":"order-tap.html","result":"order-game-result","unit":"個"},"color":{"title":"色当て","file":"color-match.html","result":"color-game-result","unit":"問"},"chest":{"title":"宝箱えらび","file":"treasure-choice.html","result":"chest-game-result","unit":"回"}});games.formwork={title:'型枠の組立て',file:'formwork-game.html',result:'formwork-game-result',unit:'点'};let currentGame='math',rankingGame='math';let identity=null,busy=false,loading=false,automaticRankingGame=null;const pending=new Map();
  async function request(payload){if(!API)return {ok:false,error:'共有先が未設定です'};let timer;try{return await Promise.race([callShared(payload),new Promise(resolve=>{timer=setTimeout(()=>resolve({ok:false,error:'通信がタイムアウトしました'}),25000)})]);}catch{return {ok:false,error:'通信できませんでした'};}finally{clearTimeout(timer);}}
  async function authenticate(){if(!await verifyPunchIdentity())return null;const r=readDeviceRegistration();if(!r||r.name!==byId('employee').value)return null;return {name:r.name,deviceToken:r.deviceToken};}
  function render(rows){const box=byId('mathRankingRows');box.replaceChildren();if(!rows.length){box.textContent='登録メンバーがいません';return;}const table=document.createElement('table');table.className='report';const head=document.createElement('tr');for(const label of ['順位','メンバー','最高得点']){const th=document.createElement('th');th.textContent=label;head.append(th);}table.append(head);for(const row of rows){const tr=document.createElement('tr');for(const text of [row.rank===null?'—':row.rank+'位',row.name,row.score===null?'未プレイ':row.score+games[rankingGame].unit]){const td=document.createElement('td');td.textContent=text;tr.append(td);}table.append(tr);}box.append(table);}
  async function showRanking(gameId=rankingGame){if(loading)return;rankingGame=gameId;byId('gameRankingTitle').textContent=games[gameId].title+'・ランキング';if(!API){rankingDialog.showModal();byId('mathRankingRows').textContent='別版用の共有先を設定すると、登録メンバーのランキングが表示されます。';return;}if(loading)return;loading=true;try{const who=await authenticate();if(!who)return;const frame=byId('mathGameFrame');frame?.contentWindow.postMessage({type:'math-drop-pause'},'*');if(!rankingDialog.open)rankingDialog.showModal();byId('mathRankingRows').textContent='読み込み中…';const result=await request({action:'mathGameRanking',gameId:rankingGame,...who});if(result.ok&&Array.isArray(result.ranking))render(result.ranking);else byId('mathRankingRows').textContent=(result.error||'ランキングを取得できません。Apps Scriptの更新を確認してください');}finally{loading=false;}}
  async function savePending(){if(busy||!pending.size)return;busy=true;status.textContent='得点を保存中…';byId('mathGameRetry').hidden=true;let failed=false,lastSaved=null;for(const [key,entry] of [...pending]){const result=await request({action:'saveMathGameScore',...entry});if(!result.ok||!Array.isArray(result.ranking)){status.textContent='得点を保存できません：'+(result.error||'Apps Scriptを更新してください');failed=true;if(automaticRankingGame===entry.gameId&&rankingDialog.open){const box=byId('mathRankingRows');box.textContent=status.textContent;const retry=document.createElement('button');retry.className='primary';retry.textContent='保存してランキングを表示';retry.onclick=()=>{box.textContent='得点を保存中…';savePending();};box.append(document.createElement('br'),retry);}break;}if(pending.get(key)===entry)pending.delete(key);lastSaved=entry;if(automaticRankingGame===entry.gameId&&rankingDialog.open&&rankingGame===entry.gameId)render(result.ranking);}busy=false;byId('mathGameRetry').hidden=!pending.size;if(!failed){status.textContent=(lastSaved?games[lastSaved.gameId].title+'の':'')+'最高得点をランキングに保存しました';if(pending.size)savePending();}}
  function gameButton(gameId){if(['order','color','chest','formwork'].includes(gameId))return byId(gameId+'GameOpen');return byId(gameId==='maze'?'mazeGameOpen':gameId==='mole'?'moleGameOpen':gameId==='drop'?'dropGameOpen':'mathGameOpen')}
  async function openGame(gameId){const trigger=gameButton(gameId);if(trigger.disabled)return;trigger.disabled=true;try{const who=await authenticate();if(!who)return;identity=who;currentGame=gameId;const frame=document.createElement('iframe');frame.id='mathGameFrame';frame.title=games[gameId].title;frame.setAttribute('sandbox','allow-scripts');frame.src='./'+games[gameId].file;dialog.append(frame);dialog.showModal();byId('mathGamePlayer').textContent=games[gameId].title+' ・ '+who.name+' さん';}finally{trigger.disabled=false;}}
  open.addEventListener('click',()=>openGame('math'));byId('moleGameOpen').addEventListener('click',()=>openGame('mole'));byId('dropGameOpen').addEventListener('click',()=>openGame('drop'));byId('mazeGameOpen').addEventListener('click',()=>openGame('maze'));
  for(const id of ['order','color','chest','formwork']){byId(id+'GameOpen').addEventListener('click',()=>openGame(id));byId(id+'RankingOpen')?.addEventListener('click',()=>showRanking(id));}
  byId('mathGameClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{byId('mathGameFrame')?.remove();const trigger=gameButton(currentGame);identity=null;trigger.focus();});
  window.addEventListener('message',event=>{const frame=byId('mathGameFrame'),message=event.data;if(!frame||event.source!==frame.contentWindow||event.origin!=='null'||!identity||message?.type!==games[currentGame].result||!Number.isInteger(message.score)||message.score<0||message.score>100000)return;if(!API){status.textContent='おためしの得点：'+message.score+games[currentGame].unit+'（ランキングには保存されません）';return;}automaticRankingGame=currentGame;rankingGame=currentGame;byId('gameRankingTitle').textContent=games[currentGame].title+'・ランキング';if(!rankingDialog.open)rankingDialog.showModal();byId('mathRankingRows').textContent='得点を保存してランキングを読み込んでいます…';const key=currentGame+':'+identity.name;const prior=pending.get(key);if(!prior||message.score>prior.score)pending.set(key,{...identity,gameId:currentGame,score:message.score});savePending();});
  byId('mathRankingOpen').addEventListener('click',()=>showRanking('math'));byId('moleRankingOpen').addEventListener('click',()=>showRanking('mole'));byId('dropRankingOpen').addEventListener('click',()=>showRanking('drop'));byId('mazeRankingOpen').addEventListener('click',()=>showRanking('maze'));byId('mathRankingRefresh').addEventListener('click',()=>showRanking());byId('mathRankingClose').addEventListener('click',()=>rankingDialog.close());byId('mathGameRetry').addEventListener('click',savePending);
})();
